[project]
name = "gro-store"
version = "0.1.0"
description = "online_store"
requires-python = ">=3.13"

dependencies = [
    "django (>=5.2.7,<6.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "pillow>=11.2.1,<12.0.0",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "django-filter (>=25.1,<26.0)",
    "drf-spectacular (>=0.28.0,<0.29.0)",
    "django-cors-headers (>=4.7.0,<5.0.0)",
    "environs (>=14.3.0,<15.0.0)",
    "ruff>=0.14.10",
    "uvicorn>=0.38.0",
    "unidecode>=1.4.0",
    "django-imagekit>=6.1.0",
]


[tool.ruff]
line-length = 119
indent-width = 4
target-version = "py313"
exclude = [
    "src/tests/**",
    ".git",
    ".venv",
    "**/__pycache__/**",
    "**/migrations/*"
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "C4",
    "S",
    "T20",
    "T10",
]
ignore = [
    "E501",
    "S110",
]

lint-selector = "all"
fix-selector = "all"

[tool.ruff.isort]
known-first-party = ["gro-store"]
line-length = 119
multi-line-output = 3
skip-gitignore = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
